import Head from 'next/head'
import * as Mui from '@mui/material'
import ResponsiveAppBar from '@/components/appBar/ResponsiveAppBar'
import { useEffect, useRef, useState } from 'react';
import LoginModal from '@/components/modal/LoginModal';
import { useRouter } from 'next/router';
import isLoggedIn from './isLoggedIn';

export default function Home() {  

  const divRef = useRef(null);
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [modalOpen, setModalOpen] = useState(false);
  const [submitClicked, setSubmitClicked] = useState(false)
  const [redirectToAddTicket, setRedirectToAddTicket] = useState(false)
  
  const [subject, setSubject] = useState('');
  const [description, setDescription] = useState(''); 

  useEffect(() => {    
    const ini = async () => {
      const isAuthrorized = await isLoggedIn();      
      if (isAuthrorized[0]) {
        await router.replace(`/dashboard/${isAuthrorized[1].toString().toLowerCase()}`);
      }
      else {
        setLoading(false);        
      }
    };
    ini();

  }, [])  

  const onSign = () => {    
    setModalOpen(true);
  }  

  useEffect(() => {

    if(router.query.openSignIn) {
      setModalOpen(true);
    }

  }, [router.query])

  const handleSubmit = () => {

    if (!subject || !description) {
      setSubmitClicked(true);    
    }
    else {

      setSubmitClicked(false);      
      localStorage.setItem('subject', subject);
      localStorage.setItem('description', description);
      setRedirectToAddTicket(true);
      setModalOpen(true);
    } 
  }

  return ( 
    !loading && (   
    <div ref={divRef} style={{ backgroundColor: "rgb(234, 234, 238)" }}>
      <Head>      
        <title>Service Charge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/appLogoWhite.png" />        
      </Head>          
      <div className="content-wrapper">      
      <ResponsiveAppBar onSignIn={onSign} />
      <section>                  
        <div className='d-flex align-items-end' style={{height: '85vh' }}>                            
          <div
          className="d-flex justify-content-center align-items-center h-100 w-100"
          style={{
            backgroundImage: "url(/backgroundIndex.jpg)",
            backgroundSize: "cover",
            backgroundPosition: "bottom",
          }}
        >        
          <h1 className='appTitle pb-5'>Service Charge<br/>Application</h1>
        </div>
      </div>             
      </section>            
      <section>
      <div className="d-flex flex-column flex-xxl-row">
        <div className="col-12 col-xxl-6" style={{ backgroundColor: "rgb(234, 234, 238)" }}>
          <div className="d-flex flex-column">
            <h1 className="mt-5 ms-5 ps-2 mb-4" style={{ fontSize: "3em", fontFamily: "Calibri" }}>Ticket Request</h1>                        
            <p className="mx-5 ps-4 text-justify" style={{ fontSize: "1.2em", lineHeight: "1.5" }}>
            Use this form to request support for any service-related issues or 
            inquiries. Our team will respond to your request as soon as possible. 
            Please provide a detailed description of your issue or inquiry to help 
            us provide you with the best possible solution.</p>
          </div>
        </div>
        <div className="col-12 col-xxl-6 pt-5" style={{ backgroundColor: "rgb(234, 234, 238)" }}>
          <div className='d-flex flex-column'>
          <h1 className="ms-5 ps-2 mb-4" style={{ fontSize: "3em", fontFamily: "Calibri" }}>Submit a Ticket</h1>            

            <Mui.TextField
              sx={{backgroundColor: "rgb(255, 255, 255)"}}
              className='mx-5'              
              label="Subject"                            
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              error={submitClicked && !subject}              
            />

            <Mui.TextField
              className='mx-5 mt-4'              
              label="Description"
              multiline
              rows={6}                            
              sx={{backgroundColor: "rgb(255, 255, 255)"}}
              value={description}
              onChange={(e) => setDescription(e.target.value)}       
              error={submitClicked && !description}              
            />     
            <button className='m-5 btn btn-dark p-3' onClick={handleSubmit}>Submit</button>
          </div>
        </div>
      </div>      
    </section>    
    <footer>         
      <div className='d-flex flex-column' style={{backgroundColor: "rgb(234, 234, 238)"}}>
        <div className='d-flex flex-column flex-xl-row' style={{backgroundColor: "rgb(234, 234, 238)"}}>    
          
          <div className="d-flex col-xl-4 flex-column mt-5" style={{ backgroundColor: "rgb(234, 234, 238)" }}>          
            <h1 className='d-flex mx-auto'>Alliance</h1>
            <div className='d-flex mt-4 ms-5'>
              <img className='img-fluid' src='/allianceLogo.png' style={{height: '60px', width: '70px'}}/>  
              <p className='mx-3'>
              {
                `Alliance Software, Inc. is a global IT services and solutions company. Alliance was established in 
                2000 and has since grown to become one of the Philippines' largest and most respected independent 
                software development outsourcing company.                        `
              }                
              </p>
            </div>            
          </div> 

          <div className="d-flex col-xl-4 flex-column mt-5" style={{ backgroundColor: "rgb(234, 234, 238)" }}>
            <h1 className='mx-auto'>About</h1>
            <h5 className='mx-auto my-3'>Made by:</h5>
            <a className='mx-auto mt-1' href="https://www.facebook.com/jl.vincent.92" target="_blank">Lj Vincent Tudtud</a>
            <a className='mx-auto mt-1' href="https://www.facebook.com/joergeryan.lou" target="_blank">Joerge Ryan Lou</a>
            <a className='mx-auto mt-1' href="https://www.facebook.com/cathgadiane" target="_blank">Cathleen Rose Gadiane</a>
          </div>

          <div className="d-flex col-xl-4 flex-column mt-5" style={{ backgroundColor: "rgb(234, 234, 238)" }}>
            <h1 className='mx-auto'>Contact</h1>
            <img className='img-fluid mx-auto mt-3 mb-2' src='/appLogoBlack.png' style={{height: '60px', width: '70px'}}/>  
            <a className='mx-auto mt-3' href="#">alliance.servicecharge.gmail.com</a>            
          </div>

        </div>  
        <hr/>                
        <a className='mx-auto text-decoration-none mt-3 mb-4 text-black'>© Team Seven</a>  
        <LoginModal modalOpen={modalOpen} setModalOpen={setModalOpen} redirectToAddTicket={redirectToAddTicket}/>
      </div>          
    </footer> 
    </div>                 
    </div>    
    )   
  )
}
